#!/usr/bin/env bash
# tools/git/merge.sh
# Generate .gitconfig with [include] directives for each layer

set -euo pipefail

IFS=':' read -ra layer_names <<< "$LAYERS"
IFS=':' read -ra paths <<< "$LAYER_PATHS"

# Ensure target directory exists
target_dir=$(dirname "$TARGET")
mkdir -p "$target_dir"

# Generate .gitconfig with include directives
cat > "$TARGET" << 'HEADER'
# Auto-generated by dotfiles layering system
# DO NOT EDIT - changes will be overwritten
#
# This file includes configs from multiple layers.
# Edit the source files in your dotfiles instead.

HEADER

for i in "${!paths[@]}"; do
    layer_path="${paths[$i]}"
    layer_name="${layer_names[$i]}"

    # Find gitconfig file in layer
    config_file=""
    for candidate in "$layer_path/.gitconfig" "$layer_path/gitconfig" "$layer_path/config"; do
        if [[ -f "$candidate" ]]; then
            config_file="$candidate"
            break
        fi
    done

    if [[ -n "$config_file" && -f "$config_file" ]]; then
        echo "# Layer: $layer_name" >> "$TARGET"
        echo "[include]" >> "$TARGET"
        echo "    path = $config_file" >> "$TARGET"
        echo "" >> "$TARGET"
        echo "[INFO] Added include for layer: $layer_name"
    else
        echo "[WARN] No gitconfig found in layer: $layer_path" >&2
    fi
done

echo "[OK] Git config written to: $TARGET"
